CREATE TABLE menus (
	id serial4 NOT NULL,
	"uuid" uuid NOT NULL DEFAULT uuid_generate_v1mc(),
	"name" TEXT NOT NULL,
	price int4 NOT NULL,
	image TEXT NOT NULL,
	description TEXT NOT NULL,
	created_at timestamp NOT NULL DEFAULT now(),
	src_doc tsvector NOT NULL GENERATED ALWAYS AS (to_tsvector('simple'::regconfig,
(name || ' '::TEXT) || description)) STORED,
	CONSTRAINT menus_pkey PRIMARY KEY (id),
	CONSTRAINT menus_uuid_key UNIQUE (uuid)
);

CREATE INDEX menu_src_doc_idx ON
menus
  USING GIN(src_doc);

INSERT
  INTO
  "menus" ("name",
  "price",
  "image",
  "description")
VALUES
  ('Margherita Pizza',
120000,
'margherita.jpg',
'Classic tomato and mozzarella pizza'),
  ('Chicken Alfredo Pasta',
150000,
'chicken_alfredo.jpg',
'Creamy Alfredo sauce with grilled chicken'),
  ('Caesar Salad',
80000,
'caesar_salad.jpg',
'Fresh romaine lettuce with Caesar dressing'),
  ('Cheeseburger',
100000,
'cheeseburger.jpg',
'Juicy beef patty with melted cheese'),
  ('Chocolate Brownie Sundae',
70000,
'brownie_sundae.jpg',
'Warm chocolate brownie with vanilla ice cream'),
  ('Vegetarian Pizza',
130000,
'vegetarian_pizza.jpg',
'Assorted vegetables on a crispy crust'),
  ('Spaghetti Bolognese',
140000,
'spaghetti_bolognese.jpg',
'Hearty meat sauce served over spaghetti'),
  ('Greek Salad',
90000,
'greek_salad.jpg',
'Crisp vegetables with feta cheese and olives'),
  ('BBQ Bacon Burger',
110000,
'bbq_bacon_burger.jpg',
'Grilled burger with BBQ sauce and bacon'),
  ('Fruit Salad',
60000,
'fruit_salad.jpg',
'Fresh assortment of seasonal fruits'),
  ('Pepperoni Pizza',
120000,
'pepperoni_pizza.jpg',
'Classic pizza topped with pepperoni slices'),
  ('Shrimp Scampi Pasta',
160000,
'shrimp_scampi.jpg',
'Garlic butter shrimp over linguine pasta'),
  ('Caprese Salad',
80000,
'caprese_salad.jpg',
'Tomatoes, mozzarella, and basil drizzled with balsamic glaze'),
  ('Mushroom Swiss Burger',
110000,
'mushroom_swiss_burger.jpg',
'Sautéed mushrooms and melted Swiss cheese on a burger'),
  ('Tiramisu',
70000,
'tiramisu.jpg',
'Classic Italian dessert with coffee-soaked ladyfingers'),
  ('Hawaiian Pizza',
130000,
'hawaiian_pizza.jpg',
'Pizza topped with ham, pineapple, and cheese'),
  ('Lobster Alfredo Pasta',
180000,
'lobster_alfredo.jpg',
'Creamy Alfredo with succulent lobster pieces'),
  ('Cobb Salad',
100000,
'cobb_salad.jpg',
'Avocado, bacon, chicken, and blue cheese on a bed of greens'),
  ('Veggie Burger',
90000,
'veggie_burger.jpg',
'Plant-based patty with lettuce, tomato, and pickles'),
  ('Red Velvet Cake',
80000,
'red_velvet_cake.jpg',
'Moist red velvet cake with cream cheese frosting'),
  ('Margarita Pizza',
120000,
'margarita_pizza.jpg',
'Pizza with fresh tomatoes, mozzarella, and basil'),
  ('Seafood Linguine',
170000,
'seafood_linguine.jpg',
'Mixed seafood in a white wine and garlic sauce'),
  ('Spinach and Strawberry Salad',
90000,
'spinach_strawberry_salad.jpg',
'Spinach, strawberries, and feta with balsamic vinaigrette'),
  ('Classic Cheese Pizza',
110000,
'classic_cheese_pizza.jpg',
'Simple and delicious cheese pizza'),
  ('Chicken Caesar Wrap',
100000,
'chicken_caesar_wrap.jpg',
'Grilled chicken, romaine lettuce, and Caesar dressing in a wrap'),
  ('Blueberry Cheesecake',
70000,
'blueberry_cheesecake.jpg',
'Rich and creamy cheesecake with blueberry topping'),
  ('Pesto Pasta',
130000,
'pesto_pasta.jpg',
'Pasta with fresh basil pesto and pine nuts'),
  ('Turkey Club Sandwich',
120000,
'turkey_club_sandwich.jpg',
'Triple-decker sandwich with turkey, bacon, and avocado'),
  ('Fudge Brownie Sundae',
80000,
'fudge_brownie_sundae.jpg',
'Decadent fudge brownie with ice cream and fudge sauce'),
  ('Margherita Flatbread',
100000,
'margherita_flatbread.jpg',
'Flatbread topped with tomatoes, mozzarella, and basil');