/* eslint-disable */
export default async () => {
    const t = {
        ["./outlets/dto/outlets.dto"]: await import("./outlets/dto/outlets.dto"),
        ["./menus/dto/menus.dto"]: await import("./menus/dto/menus.dto"),
        ["./auth/dto/login.dto"]: await import("./auth/dto/login.dto"),
        ["./shared/dto/basic.dto"]: await import("./shared/dto/basic.dto")
    };
    return { "@nestjs/swagger": { "models": [[import("./shared/dto/pagination.dto"), { "PaginationReqDto": { cursor: { required: false, type: () => Number }, pageSize: { required: false, type: () => Number }, search: { required: false, type: () => String, nullable: true } }, "PaginationRespDto": { nextCursor: { required: false, type: () => Number, nullable: true }, pageSize: { required: true, type: () => Number }, data: { required: true } } }], [import("./outlets/dto/outlets.dto"), { "OutletDto": { address: { required: true, type: () => String }, latitude: { required: true, type: () => Number }, longitude: { required: true, type: () => Number }, name: { required: true, type: () => String }, uuid: { required: true, type: () => String } }, "OutletRespDto": { data: { required: true, type: () => [t["./outlets/dto/outlets.dto"].OutletDto] } } }], [import("./menus/dto/menus.dto"), { "OutletMenuDto": { is_available: { required: true, type: () => Boolean }, description: { required: true, type: () => String }, image: { required: true, type: () => String }, name: { required: true, type: () => String }, uuid: { required: true, type: () => String }, price: { required: true, type: () => Number } }, "OutletMenuRespDto": { data: { required: true, type: () => [t["./menus/dto/menus.dto"].OutletMenuDto] } } }], [import("./auth/dto/login.dto"), { "LoginDto": { username: { required: true, type: () => String } }, "LoginRespDto": { accessToken: { required: true, type: () => String } } }], [import("./carts/dto/add.carts.dto"), { "AddToCartDto": { outletUuid: { required: true, type: () => String }, menuUuid: { required: true, type: () => String }, quantity: { required: true, type: () => Number, minimum: 1 } } }], [import("./shared/dto/basic.dto"), { "SuccessRespDto": { message: { required: true, type: () => String } } }]], "controllers": [[import("./outlets/outlets.controller"), { "OutletsController": { "findAll": { type: t["./outlets/dto/outlets.dto"].OutletRespDto } } }], [import("./menus/menus.controller"), { "MenusController": { "findMenusOnOutlet": { type: t["./menus/dto/menus.dto"].OutletMenuRespDto } } }], [import("./auth/auth.controller"), { "AuthController": { "login": { type: t["./auth/dto/login.dto"].LoginRespDto } } }], [import("./carts/carts.controller"), { "CartsController": { "getAll": { type: Object }, "addToCart": { type: t["./shared/dto/basic.dto"].SuccessRespDto }, "updateCartItem": { type: Object }, "deleteCartItem": { type: Object }, "deleteCart": { type: Object } } }]] } };
};